
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Status
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Status()
    {

        this.BillOfLandings = new HashSet<BillOfLanding>();

    }


    public int Id { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BillOfLanding> BillOfLandings { get; set; }

}

}
